// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/candidates": {
            "get": {
                "description": "Returns a paginated list of candidates with interview count and latest outcome",
                "produces": ["application/json"],
                "tags": ["candidates"],
                "summary": "List candidates",
                "parameters": [
                    {"type": "integer", "default": 50, "description": "Max results to return", "name": "limit", "in": "query"},
                    {"type": "integer", "default": 0, "description": "Offset for pagination", "name": "offset", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/api.ListCandidatesResponse"}},
                    "500": {"description": "Internal Server Error", "schema": {"type": "object", "additionalProperties": {"type": "string"}}}
                }
            }
        },
        "/candidates/{id}": {
            "get": {
                "description": "Returns full candidate profile including all interview records",
                "produces": ["application/json"],
                "tags": ["candidates"],
                "summary": "Get candidate detail",
                "parameters": [
                    {"type": "integer", "description": "Candidate ID", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/storage.CandidateDetail"}},
                    "400": {"description": "Bad Request", "schema": {"type": "object", "additionalProperties": {"type": "string"}}},
                    "404": {"description": "Not Found", "schema": {"type": "object", "additionalProperties": {"type": "string"}}}
                }
            }
        },
        "/candidates/{id}/similar": {
            "get": {
                "description": "Returns candidates whose embedding vector is closest to the given candidate's vector. Requires the candidate to have been embedded via a CV upload.",
                "produces": ["application/json"],
                "tags": ["candidates"],
                "summary": "Find similar candidates",
                "parameters": [
                    {"type": "integer", "description": "Candidate ID", "name": "id", "in": "path", "required": true},
                    {"type": "integer", "default": 5, "description": "Number of similar candidates to return (1-20)", "name": "top_k", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/api.SimilarCandidatesResponse"}},
                    "400": {"description": "Bad Request", "schema": {"type": "object", "additionalProperties": {"type": "string"}}},
                    "500": {"description": "Internal Server Error", "schema": {"type": "object", "additionalProperties": {"type": "string"}}}
                }
            }
        },
        "/candidates/{id}/interviews": {
            "post": {
                "description": "Adds a new interview record for a candidate and queues an embedding re-generation",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["candidates"],
                "summary": "Create interview",
                "parameters": [
                    {"type": "integer", "description": "Candidate ID", "name": "id", "in": "path", "required": true},
                    {"description": "Interview data", "name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/api.InterviewRequest"}}
                ],
                "responses": {
                    "201": {"description": "Created", "schema": {"type": "object", "additionalProperties": true}},
                    "400": {"description": "Bad Request", "schema": {"type": "object", "additionalProperties": {"type": "string"}}},
                    "500": {"description": "Internal Server Error", "schema": {"type": "object", "additionalProperties": {"type": "string"}}}
                }
            }
        },
        "/candidates/{id}/interviews/{iid}": {
            "put": {
                "description": "Updates an existing interview record and queues an embedding re-generation",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["candidates"],
                "summary": "Update interview",
                "parameters": [
                    {"type": "integer", "description": "Candidate ID", "name": "id", "in": "path", "required": true},
                    {"type": "integer", "description": "Interview ID", "name": "iid", "in": "path", "required": true},
                    {"description": "Updated interview data", "name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/api.InterviewRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "object", "additionalProperties": true}},
                    "400": {"description": "Bad Request", "schema": {"type": "object", "additionalProperties": {"type": "string"}}},
                    "404": {"description": "Not Found", "schema": {"type": "object", "additionalProperties": {"type": "string"}}}
                }
            },
            "delete": {
                "description": "Deletes an interview record and queues an embedding re-generation",
                "tags": ["candidates"],
                "summary": "Delete interview",
                "parameters": [
                    {"type": "integer", "description": "Candidate ID", "name": "id", "in": "path", "required": true},
                    {"type": "integer", "description": "Interview ID", "name": "iid", "in": "path", "required": true}
                ],
                "responses": {
                    "204": {"description": "No Content"},
                    "400": {"description": "Bad Request", "schema": {"type": "object", "additionalProperties": {"type": "string"}}},
                    "404": {"description": "Not Found", "schema": {"type": "object", "additionalProperties": {"type": "string"}}}
                }
            }
        },
        "/cv/batch/{batch_id}": {
            "get": {
                "description": "Get the processing status of all CVs uploaded in a bulk upload batch",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cv"
                ],
                "summary": "Get batch upload status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Batch ID returned by bulk-upload",
                        "name": "batch_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cv/bulk-upload": {
            "post": {
                "description": "Upload multiple CV files at once (max 10 files, 1 MB each, 10 MB total)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cv"
                ],
                "summary": "Bulk upload CVs",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CV files (PDF, DOCX, TXT) — field name: files",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "207": {
                        "description": "Multi-Status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cv/job/{job_id}": {
            "get": {
                "description": "Get the current status of an async CV processing job",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cv"
                ],
                "summary": "Get CV processing job status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cv/upload": {
            "post": {
                "description": "Upload a CV file (PDF/DOCX) and extract entities using LLM",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cv"
                ],
                "summary": "Upload and parse CV",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CV file (PDF or DOCX)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Candidate ID (optional)",
                        "name": "candidate_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/graph/skills/popular": {
            "get": {
                "description": "Get most popular skills extracted from CVs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "Get popular skills",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Limit results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/graph/stats": {
            "get": {
                "description": "Get statistics about the knowledge graph (skill popularity, etc.)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "Get graph statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/graphrag/communities/detect": {
            "post": {
                "description": "Run Leiden algorithm to detect communities in the knowledge graph",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graphrag"
                ],
                "summary": "Detect Communities",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Hierarchy level (default: 0)",
                        "name": "level",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/graphrag/embeddings/generate": {
            "post": {
                "description": "Generate OpenAI embeddings for all nodes in the knowledge graph",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graphrag"
                ],
                "summary": "Generate Vector Embeddings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/graphrag/search": {
            "post": {
                "description": "Search candidates using natural language with Vector embeddings, Community detection, and LLM reasoning (Microsoft GraphRAG style)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graphrag"
                ],
                "summary": "GraphRAG Search (Vector + Community + LLM)",
                "parameters": [
                    {
                        "description": "Natural language search query",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GraphRAGSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search": {
            "post": {
                "description": "Search for candidates based on criteria (name, location, skills)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "candidates"
                ],
                "summary": "Search candidates",
                "parameters": [
                    {
                        "description": "Search criteria",
                        "name": "criteria",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.Criteria"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/storage.Candidate"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search/popular-queries": {
            "get": {
                "description": "Returns a list of ready-made search queries derived from the most common skills and seniority levels in the knowledge graph. Cached in-memory for 5 minutes.",
                "produces": ["application/json"],
                "tags": ["search"],
                "summary": "Get popular search queries",
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"type": "string"}}},
                    "500": {"description": "Internal Server Error", "schema": {"type": "object", "additionalProperties": {"type": "string"}}}
                }
            }
        },
        "/search/suggest": {
            "get": {
                "description": "Returns autocomplete suggestions based on a prefix. Searches skill names, company names and current positions in the knowledge graph.",
                "produces": ["application/json"],
                "tags": ["search"],
                "summary": "Autocomplete search suggestions",
                "parameters": [
                    {"type": "string", "description": "Search prefix (min 1 char)", "name": "q", "in": "query", "required": true},
                    {"type": "integer", "default": 8, "description": "Max results (1-20)", "name": "limit", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/storage.SuggestionResult"}}},
                    "400": {"description": "Bad Request", "schema": {"type": "object", "additionalProperties": {"type": "string"}}},
                    "500": {"description": "Internal Server Error", "schema": {"type": "object", "additionalProperties": {"type": "string"}}}
                }
            }
        },
        "/search/hybrid": {
            "post": {
                "description": "Search candidates using multi-source retrieval with fusion and pure LLM reranking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Hybrid Search (BM25 + Vector + Graph + LLM)",
                "parameters": [
                    {
                        "description": "Hybrid search request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.HybridSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HybridSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.FusedCandidateResponse": {
            "type": "object",
            "properties": {
                "bm25_score": {
                    "type": "number"
                },
                "communities": {
                    "description": "All matching communities",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "community": {
                    "description": "Primary community",
                    "type": "string"
                },
                "community_scores": {
                    "description": "Score for each community",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "companies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graphrag.CompanyNode"
                    }
                },
                "current_position": {
                    "type": "string"
                },
                "fusion_score": {
                    "type": "number"
                },
                "graph_score": {
                    "type": "number"
                },
                "llm_reasoning": {
                    "type": "string"
                },
                "llm_score": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "person_id": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "seniority": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graphrag.SkillNode"
                    }
                },
                "total_experience_years": {
                    "type": "integer"
                },
                "vector_score": {
                    "type": "number"
                }
            }
        },
        "api.GraphRAGSearchRequest": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string"
                }
            }
        },
        "api.HybridSearchRequest": {
            "type": "object",
            "properties": {
                "bm25_weight": {
                    "description": "Default: 0.3",
                    "type": "number"
                },
                "final_top_n": {
                    "description": "Max candidates to send to LLM (default: 0 = all)",
                    "type": "integer"
                },
                "graph_weight": {
                    "description": "Default: 0.3",
                    "type": "number"
                },
                "query": {
                    "type": "string"
                },
                "top_k": {
                    "description": "Per-source retrieval limit (default: 100)",
                    "type": "integer"
                },
                "vector_weight": {
                    "description": "Default: 0.4",
                    "type": "number"
                }
            }
        },
        "api.HybridSearchResponse": {
            "type": "object",
            "properties": {
                "candidates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.FusedCandidateResponse"
                    }
                },
                "config": {
                    "$ref": "#/definitions/graphrag.HybridSearchConfig"
                },
                "method": {
                    "type": "string"
                },
                "processing_time": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                },
                "total_found": {
                    "type": "integer"
                }
            }
        },
        "graphrag.CompanyNode": {
            "type": "object",
            "properties": {
                "is_current": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "graphrag.HybridSearchConfig": {
            "type": "object",
            "properties": {
                "bm25Weight": {
                    "description": "Default: 0.3",
                    "type": "number",
                    "format": "float64"
                },
                "communityThreshold": {
                    "description": "Auto-enable community filter at this candidate count (default: 50)",
                    "type": "integer"
                },
                "finalTopN": {
                    "description": "How many to send to LLM for reranking",
                    "type": "integer"
                },
                "graphWeight": {
                    "description": "Default: 0.3",
                    "type": "number",
                    "format": "float64"
                },
                "topK": {
                    "description": "How many candidates to retrieve from each source",
                    "type": "integer"
                },
                "useCommunityFilter": {
                    "description": "Enable community-based filtering (default: false, enabled at 50+ candidates)",
                    "type": "boolean"
                },
                "vectorWeight": {
                    "description": "Default: 0.4",
                    "type": "number",
                    "format": "float64"
                }
            }
        },
        "graphrag.SkillNode": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "proficiency": {
                    "type": "string"
                },
                "years_of_experience": {
                    "type": "integer"
                }
            }
        },
        "storage.Candidate": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "experience": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resume_downloaded_at": {
                    "type": "string"
                },
                "resume_file_path": {
                    "type": "string"
                },
                "resume_url": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "storage.Criteria": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.InterviewRequest": {
            "type": "object",
            "required": ["interview_date"],
            "properties": {
                "interview_date": {"type": "string", "description": "Required. Format YYYY-MM-DD"},
                "team": {"type": "string"},
                "interviewer_name": {"type": "string"},
                "interview_type": {"type": "string", "description": "One of: technical, hr, case_study, other"},
                "notes": {"type": "string"},
                "outcome": {"type": "string", "description": "One of: passed, failed, pending"}
            }
        },
        "api.ListCandidatesResponse": {
            "type": "object",
            "properties": {
                "candidates": {"type": "array", "items": {"$ref": "#/definitions/storage.CandidateListItem"}},
                "total": {"type": "integer"},
                "limit": {"type": "integer"},
                "offset": {"type": "integer"}
            }
        },
        "storage.Interview": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "candidate_id": {"type": "integer"},
                "interview_date": {"type": "string"},
                "team": {"type": "string"},
                "interviewer_name": {"type": "string"},
                "interview_type": {"type": "string", "description": "technical, hr, case_study, other"},
                "notes": {"type": "string"},
                "outcome": {"type": "string", "description": "passed, failed, pending"},
                "created_at": {"type": "string"},
                "updated_at": {"type": "string"}
            }
        },
        "storage.CandidateDetail": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "name": {"type": "string"},
                "email": {"type": "string"},
                "phone": {"type": "string"},
                "location": {"type": "string"},
                "graph_node_id": {"type": "integer"},
                "current_position": {"type": "string"},
                "seniority": {"type": "string"},
                "interviews": {"type": "array", "items": {"$ref": "#/definitions/storage.Interview"}},
                "created_at": {"type": "string"}
            }
        },
        "storage.SuggestionResult": {
            "type": "object",
            "properties": {
                "text": {"type": "string"},
                "type": {"type": "string", "description": "One of: skill, company, position"}
            }
        },
        "storage.SimilarCandidate": {
            "type": "object",
            "properties": {
                "candidate_id": {"type": "integer"},
                "name": {"type": "string"},
                "current_position": {"type": "string"},
                "seniority": {"type": "string"},
                "top_skills": {"type": "array", "items": {"type": "string"}},
                "similarity": {"type": "number", "description": "Cosine similarity (0-1)"}
            }
        },
        "api.SimilarCandidatesResponse": {
            "type": "object",
            "properties": {
                "source_candidate_id": {"type": "integer"},
                "top_k": {"type": "integer"},
                "similar": {"type": "array", "items": {"$ref": "#/definitions/storage.SimilarCandidate"}}
            }
        },
        "storage.CandidateListItem": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "name": {"type": "string"},
                "current_position": {"type": "string"},
                "seniority": {"type": "string"},
                "interview_count": {"type": "integer"},
                "latest_outcome": {"type": "string"},
                "created_at": {"type": "string"}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "cv-search-production.up.railway.app",
	BasePath:         "/api",
	Schemes:          []string{"https"},
	Title:            "CV Search & GraphRAG API",
	Description:      "AI-powered CV search system with GraphRAG and Hybrid Search capabilities",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
